apiVersion: apps/v1
kind: Deployment
metadata:
  name: carinfo
spec:
  selector:
    matchLabels:
      app: carinfo
  replicas: 2
  template:
    metadata:
      labels:
        app: carinfo
    spec:
      containers:
        - name: carinfo
          image: lpstoyanov/car-info:sha-74d1117ce158972aa3951fa88e016cb05ad024a8
          ports:
            - containerPort: 8080