apiVersion: v1
kind: Service
metadata:
  labels:
    app: carinfo
  name: carinfo-service
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: nginx
  type: LoadBalancer