apiVersion: apps/v1
kind: Deployment
metadata:
  name: carinfo-${STAGE}
spec:
  selector:
    matchLabels:
      app: carinfo-${STAGE}
  replicas: ${REPLICAS}
  template:
    metadata:
      labels:
        app: carinfo-${STAGE}
    spec:
      nodeSelector:
        environment: ${NODE}
      containers:
        - name: carinfo-${STAGE}
          image: lpstoyanov/car-info:${GIT_SHA}
          ports:
            - containerPort: 8080