apiVersion: apps/v1
kind: Deployment
metadata:
  name: carinfo
spec:
  selector:
    matchLabels:
      app: carinfo
  replicas: 2
  template:
    metadata:
      labels:
        app: carinfo
    spec:
      containers:
        - name: carinfo
          image: ${IMAGE_KEY}
          ports:
            - containerPort: 8080