apiVersion: v1
kind: Service
metadata:
  labels:
    app: carinfo-${STAGE}
  name: carinfo-${STAGE}-load-balancer
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: carinfo-${STAGE}
  type: LoadBalancer